apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-01-06T09:19:01Z"
  name: webapp-service
  namespace: default
  resourceVersion: "740"
  uid: 46aadff2-da1d-4500-9941-0f27ea795fab
spec:
  clusterIP: 10.43.61.197
  clusterIPs:
  - 10.43.61.197
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
